In [1]:
from pyspark.sql import functions as f

In [8]:
df_curso = (
    spark
    .read
    .options(header=True, sep='|')
    .csv('/home/rafael/Downloads/microdados_educacao_superior_2019/Microdados_Educaç╞o_Superior_2019/dados/SUP_CURSO_2019.CSV')
)

In [9]:
df_curso.printSchema()

root
 |-- NU_ANO_CENSO: string (nullable = true)
 |-- CO_IES: string (nullable = true)
 |-- TP_CATEGORIA_ADMINISTRATIVA: string (nullable = true)
 |-- TP_ORGANIZACAO_ACADEMICA: string (nullable = true)
 |-- CO_LOCAL_OFERTA: string (nullable = true)
 |-- CO_UF: string (nullable = true)
 |-- CO_MUNICIPIO: string (nullable = true)
 |-- IN_CAPITAL: string (nullable = true)
 |-- CO_CURSO: string (nullable = true)
 |-- NO_CURSO: string (nullable = true)
 |-- TP_SITUACAO: string (nullable = true)
 |-- CO_CINE_ROTULO: string (nullable = true)
 |-- TP_GRAU_ACADEMICO: string (nullable = true)
 |-- TP_MODALIDADE_ENSINO: string (nullable = true)
 |-- TP_NIVEL_ACADEMICO: string (nullable = true)
 |-- IN_GRATUITO: string (nullable = true)
 |-- TP_ATRIBUTO_INGRESSO: string (nullable = true)
 |-- NU_CARGA_HORARIA: string (nullable = true)
 |-- DT_INICIO_FUNCIONAMENTO: string (nullable = true)
 |-- DT_AUTORIZACAO_CURSO: string (nullable = true)
 |-- IN_AJUDA_DEFICIENTE: string (nullable = true)
 |-- IN_MATERIAL_DIGITAL: string (nullable = true)
 |-- IN_MATERIAL_AMPLIADO: string (nullable = true)
 |-- IN_MATERIAL_TATIL: string (nullable = true)
 |-- IN_MATERIAL_IMPRESSO: string (nullable = true)
 |-- IN_MATERIAL_AUDIO: string (nullable = true)
 |-- IN_MATERIAL_BRAILLE: string (nullable = true)
 |-- IN_MATERIAL_LIBRAS: string (nullable = true)
 |-- IN_DISCIPLINA_LIBRAS: string (nullable = true)
 |-- IN_TRADUTOR_LIBRAS: string (nullable = true)
 |-- IN_GUIA_INTERPRETE: string (nullable = true)
 |-- IN_RECURSOS_COMUNICACAO: string (nullable = true)
 |-- IN_RECURSOS_INFORMATICA: string (nullable = true)
 |-- IN_INTEGRAL: string (nullable = true)
 |-- IN_MATUTINO: string (nullable = true)
 |-- IN_VESPERTINO: string (nullable = true)
 |-- IN_NOTURNO: string (nullable = true)
 |-- NU_INTEGRALIZACAO_INTEGRAL: string (nullable = true)
 |-- NU_INTEGRALIZACAO_MATUTINO: string (nullable = true)
 |-- NU_INTEGRALIZACAO_VESPERTINO: string (nullable = true)
 |-- NU_INTEGRALIZACAO_NOTURNO: string (nullable = true)
 |-- NU_INTEGRALIZACAO_EAD: string (nullable = true)
 |-- IN_OFERECE_DISC_SEMI_PRES: string (nullable = true)
 |-- NU_PERC_CARGA_SEMI_PRES: string (nullable = true)
 |-- IN_POSSUI_LABORATORIO: string (nullable = true)
 |-- QT_INSC_VAGA_NOVA_INTEGRAL: string (nullable = true)
 |-- QT_INSC_VAGA_NOVA_MATUTINO: string (nullable = true)
 |-- QT_INSC_VAGA_NOVA_VESPERTINO: string (nullable = true)
 |-- QT_INSC_VAGA_NOVA_NOTURNO: string (nullable = true)
 |-- QT_INSC_VAGA_NOVA_EAD: string (nullable = true)
 |-- QT_INSC_VAGA_REMAN_INTEGRAL: string (nullable = true)
 |-- QT_INSC_VAGA_REMAN_MATUTINO: string (nullable = true)
 |-- QT_INSC_VAGA_REMAN_VESPERTINO: string (nullable = true)
 |-- QT_INSC_VAGA_REMAN_NOTURNO: string (nullable = true)
 |-- QT_INSC_VAGA_REMAN_EAD: string (nullable = true)
 |-- QT_INSC_PROG_ESP_INTEGRAL: string (nullable = true)
 |-- QT_INSC_PROG_ESP_MATUTINO: string (nullable = true)
 |-- QT_INSC_PROG_ESP_VESPERTINO: string (nullable = true)
 |-- QT_INSC_PROG_ESP_NOTURNO: string (nullable = true)
 |-- QT_INSC_PROG_ESP_EAD: string (nullable = true)
 |-- QT_INSC_PRINCIPAL_INTEGRAL: string (nullable = true)
 |-- QT_INSC_PRINCIPAL_MATUTINO: string (nullable = true)
 |-- QT_INSC_PRINCIPAL_VESPERTINO: string (nullable = true)
 |-- QT_INSC_PRINCIPAL_NOTURNO: string (nullable = true)
 |-- QT_INSC_PRINCIPAL_EAD: string (nullable = true)
 |-- QT_INSC_OUTRA_VAGA_INTEGRAL: string (nullable = true)
 |-- QT_INSC_OUTRA_VAGA_MATUTINO: string (nullable = true)
 |-- QT_INSC_OUTRA_VAGA_VESPERTINO: string (nullable = true)
 |-- QT_INSC_OUTRA_VAGA_NOTURNO: string (nullable = true)
 |-- QT_INSC_OUTRA_VAGA_EAD: string (nullable = true)
 |-- QT_INSC_ANUAL_INTEGRAL: string (nullable = true)
 |-- QT_INSC_ANUAL_MATUTINO: string (nullable = true)
 |-- QT_INSC_ANUAL_VESPERTINO: string (nullable = true)
 |-- QT_INSC_ANUAL_NOTURNO: string (nullable = true)
 |-- QT_INSC_ANUAL_EAD: string (nullable = true)
 |-- QT_VAGAS_NOVAS_INTEGRAL: string (nullable = true)
 |-- QT_VAGAS_NOVAS_MATUTINO: string (nullable = true)
 |-- QT_VAGAS_NOVAS_VESPERTINO: string (nullable = true)
 |-- QT_VAGAS_NOVAS_NOTURNO: string (nullable = true)
 |-- QT_VAGAS_NOVAS_EAD: string (nullable = true)
 |-- QT_VAGAS_REMAN_INTEGRAL: string (nullable = true)
 |-- QT_VAGAS_REMAN_MATUTINO: string (nullable = true)
 |-- QT_VAGAS_REMAN_VESPERTINO: string (nullable = true)
 |-- QT_VAGAS_REMAN_NOTURNO: string (nullable = true)
 |-- QT_VAGAS_REMAN_EAD: string (nullable = true)
 |-- QT_VAGAS_PROG_ESP_INTEGRAL: string (nullable = true)
 |-- QT_VAGAS_PROG_ESP_MATUTINO: string (nullable = true)
 |-- QT_VAGAS_PROG_ESP_VESPERTINO: string (nullable = true)
 |-- QT_VAGAS_PROG_ESP_NOTURNO: string (nullable = true)
 |-- QT_VAGAS_PROG_ESP_EAD: string (nullable = true)
 |-- QT_VAGAS_PRINCIPAL_INTEGRAL: string (nullable = true)
 |-- QT_VAGAS_PRINCIPAL_MATUTINO: string (nullable = true)
 |-- QT_VAGAS_PRINCIPAL_VESPERTINO: string (nullable = true)
 |-- QT_VAGAS_PRINCIPAL_NOTURNO: string (nullable = true)
 |-- QT_VAGAS_PRINCIPAL_EAD: string (nullable = true)
 |-- QT_VAGAS_OUTRAS_INTEGRAL: string (nullable = true)
 |-- QT_VAGAS_OUTRAS_MATUTINO: string (nullable = true)
 |-- QT_VAGAS_OUTRAS_VESPERTINO: string (nullable = true)
 |-- QT_VAGAS_OUTRAS_NOTURNO: string (nullable = true)
 |-- QT_VAGAS_OUTRAS_EAD: string (nullable = true)
 |-- QT_VAGAS_ANUAL_INTEGRAL: string (nullable = true)
 |-- QT_VAGAS_ANUAL_MATUTINO: string (nullable = true)
 |-- QT_VAGAS_ANUAL_VESPERTINO: string (nullable = true)
 |-- QT_VAGAS_ANUAL_NOTURNO: string (nullable = true)
 |-- QT_VAGAS_ANUAL_EAD: string (nullable = true)
 |-- QT_MATRICULA_TOTAL: string (nullable = true)
 |-- QT_CONCLUINTE_TOTAL: string (nullable = true)
 |-- QT_INGRESSO_TOTAL: string (nullable = true)
 |-- QT_INGRESSO_VAGA_NOVA: string (nullable = true)
 |-- QT_INGRESSO_PROCESSO_SELETIVO: string (nullable = true)
 |-- QT_VAGA_TOTAL: string (nullable = true)
 |-- QT_INSCRITO_TOTAL: string (nullable = true)

In [10]:
df_ies = (
    spark
    .read
    .options(header=True, sep='|')
    .csv('/home/rafael/Downloads/microdados_educacao_superior_2019/Microdados_Educaç╞o_Superior_2019/dados/SUP_IES_2019.CSV')
)

In [11]:
df_ies.printSchema()

root
 |-- NU_ANO_CENSO: string (nullable = true)
 |-- CO_IES: string (nullable = true)
 |-- NO_IES: string (nullable = true)
 |-- SG_IES: string (nullable = true)
 |-- CO_MANTENEDORA: string (nullable = true)
 |-- NO_MANTENEDORA: string (nullable = true)
 |-- TP_CATEGORIA_ADMINISTRATIVA: string (nullable = true)
 |-- TP_ORGANIZACAO_ACADEMICA: string (nullable = true)
 |-- CO_REGIAO: string (nullable = true)
 |-- CO_UF: string (nullable = true)
 |-- CO_MUNICIPIO: string (nullable = true)
 |-- IN_CAPITAL: string (nullable = true)
 |-- QT_TEC_TOTAL: string (nullable = true)
 |-- QT_TEC_FUNDAMENTAL_INCOMP_FEM: string (nullable = true)
 |-- QT_TEC_FUNDAMENTAL_INCOMP_MASC: string (nullable = true)
 |-- QT_TEC_FUNDAMENTAL_COMP_FEM: string (nullable = true)
 |-- QT_TEC_FUNDAMENTAL_COMP_MASC: string (nullable = true)
 |-- QT_TEC_MEDIO_FEM: string (nullable = true)
 |-- QT_TEC_MEDIO_MASC: string (nullable = true)
 |-- QT_TEC_SUPERIOR_FEM: string (nullable = true)
 |-- QT_TEC_SUPERIOR_MASC: string (nullable = true)
 |-- QT_TEC_ESPECIALIZACAO_FEM: string (nullable = true)
 |-- QT_TEC_ESPECIALIZACAO_MASC: string (nullable = true)
 |-- QT_TEC_MESTRADO_FEM: string (nullable = true)
 |-- QT_TEC_MESTRADO_MASC: string (nullable = true)
 |-- QT_TEC_DOUTORADO_FEM: string (nullable = true)
 |-- QT_TEC_DOUTORADO_MASC: string (nullable = true)
 |-- IN_ACESSO_PORTAL_CAPES: string (nullable = true)
 |-- IN_ACESSO_OUTRAS_BASES: string (nullable = true)
 |-- IN_ASSINA_OUTRA_BASE: string (nullable = true)
 |-- IN_REPOSITORIO_INSTITUCIONAL: string (nullable = true)
 |-- IN_BUSCA_INTEGRADA: string (nullable = true)
 |-- IN_SERVICO_INTERNET: string (nullable = true)
 |-- IN_PARTICIPA_REDE_SOCIAL: string (nullable = true)
 |-- IN_CATALOGO_ONLINE: string (nullable = true)
 |-- QT_PERIODICO_ELETRONICO: string (nullable = true)
 |-- QT_LIVRO_ELETRONICO: string (nullable = true)
 |-- TP_REFERENTE: string (nullable = true)
 |-- VL_RECEITA_PROPRIA: string (nullable = true)
 |-- VL_RECEITA_TRANSFERENCIA: string (nullable = true)
 |-- VL_RECEITA_OUTRA: string (nullable = true)
 |-- VL_DESPESA_PESSOAL_DOCENTE: string (nullable = true)
 |-- VL_DESPESA_PESSOAL_TECNICO: string (nullable = true)
 |-- VL_DESPESA_PESSOAL_ENCARGO: string (nullable = true)
 |-- VL_DESPESA_CUSTEIO: string (nullable = true)
 |-- VL_DESPESA_INVESTIMENTO: string (nullable = true)
 |-- VL_DESPESA_PESQUISA: string (nullable = true)
 |-- VL_DESPESA_OUTRA: string (nullable = true)

In [16]:
df = df_curso.join(df_ies, 'CO_IES', 'LEFT')

In [27]:
df.createOrReplaceTempView('curso')

In [34]:
spark.sql(
'''
    select count(distinct CO_CURSO), CO_REGIAO
    from curso
    where upper(NO_CURSO) = 'DIREITO'
    group by CO_REGIAO
'''
).toPandas().style

In [23]:
spark.sql(
'''
    select sum(QT_INSCRITO_TOTAL) qtd, no_curso
    from curso
    group by no_curso 
    order by qtd desc
'''
).toPandas().style